/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.sql.*; 
import javax.swing.JOptionPane; 
import koneksi.koneksi;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sabdha
 */
public class TambahBarang extends javax.swing.JFrame {

    /**
     * Creates new form barang
     */
    public TambahBarang() {
        initComponents();
         kosong(); 
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
protected void kosong(){ 
          txtkode.setText(""); 
          cbkategori.setSelectedItem(null);
          txtnama.setText("");
          txtjenisataulensa.setText("");
          txthargabeli.setText("");
          txthargajual.setText("");
          txthargabeli.setText(""); 
          txtstok.setText("");
          txtketerangan.setText("");
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        roundedPanel1 = new custom_palette.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtkode = new custom_palette.RoundedTextField();
        txtjenisataulensa = new custom_palette.RoundedTextField();
        txthargabeli = new custom_palette.RoundedTextField();
        txtstok = new custom_palette.RoundedTextField();
        btntambah = new custom_palette.RoundedButton();
        cbkategori = new javax.swing.JComboBox<>();
        txtnama = new custom_palette.RoundedTextField();
        txthargajual = new custom_palette.RoundedTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtketerangan = new javax.swing.JTextArea();
        cancelButton = new custom_palette.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 241, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 832));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-box2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 171, 142));
        jLabel2.setText("Manajemen Inventaris");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 37, 223, 25));

        jSeparator1.setBackground(new java.awt.Color(136, 171, 142));
        jSeparator1.setForeground(new java.awt.Color(136, 171, 142));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 72, 291, 10));

        roundedPanel1.setBackground(new java.awt.Color(136, 171, 142));
        roundedPanel1.setForeground(new java.awt.Color(136, 171, 142));
        roundedPanel1.setCornerRadius(15);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/amico1.png"))); // NOI18N
        roundedPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 121, 392, 342));

        jLabel4.setBackground(new java.awt.Color(238, 231, 218));
        jLabel4.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 231, 218));
        jLabel4.setText("TAMBAH DATA BARANG");
        roundedPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 38, 412, 38));

        jLabel5.setBackground(new java.awt.Color(238, 231, 218));
        jLabel5.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 231, 218));
        jLabel5.setText("Kode Barang");
        roundedPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 96, 111, 21));

        jLabel6.setBackground(new java.awt.Color(238, 231, 218));
        jLabel6.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 231, 218));
        jLabel6.setText("Lensa");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        roundedPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 235, 110, 21));

        jLabel7.setBackground(new java.awt.Color(238, 231, 218));
        jLabel7.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 231, 218));
        jLabel7.setText("Kategori");
        roundedPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 137, 111, 21));

        jLabel8.setBackground(new java.awt.Color(238, 231, 218));
        jLabel8.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 231, 218));
        jLabel8.setText("Harga Jual");
        roundedPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 305, 111, 21));

        jLabel9.setBackground(new java.awt.Color(238, 231, 218));
        jLabel9.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(238, 231, 218));
        jLabel9.setText("Stok");
        roundedPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 352, 111, 21));

        jLabel10.setBackground(new java.awt.Color(238, 231, 218));
        jLabel10.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(238, 231, 218));
        jLabel10.setText("Nama/Merk");
        roundedPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 179, 111, 21));

        jLabel11.setBackground(new java.awt.Color(238, 231, 218));
        jLabel11.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(238, 231, 218));
        jLabel11.setText("Jenis Barang/");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        roundedPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 217, 110, 21));

        jLabel12.setBackground(new java.awt.Color(238, 231, 218));
        jLabel12.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 231, 218));
        jLabel12.setText("Harga Beli");
        roundedPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 263, 111, 21));

        txtkode.setBackground(new java.awt.Color(238, 231, 218));
        txtkode.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtkode.setLineColor(new java.awt.Color(238, 231, 218));
        txtkode.setSelectionColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 96, 173, 21));

        txtjenisataulensa.setBackground(new java.awt.Color(238, 231, 218));
        txtjenisataulensa.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtjenisataulensa.setLineColor(new java.awt.Color(238, 231, 218));
        txtjenisataulensa.setSelectionColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(txtjenisataulensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 225, 173, 21));

        txthargabeli.setBackground(new java.awt.Color(238, 231, 218));
        txthargabeli.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txthargabeli.setLineColor(new java.awt.Color(238, 231, 218));
        txthargabeli.setSelectionColor(new java.awt.Color(238, 231, 218));
        txthargabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargabeliActionPerformed(evt);
            }
        });
        roundedPanel1.add(txthargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 263, 173, 21));

        txtstok.setBackground(new java.awt.Color(238, 231, 218));
        txtstok.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtstok.setLineColor(new java.awt.Color(238, 231, 218));
        txtstok.setSelectionColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 352, 173, 21));

        btntambah.setForeground(new java.awt.Color(136, 171, 142));
        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/material-symbols_tambah.png"))); // NOI18N
        btntambah.setText("Tambah");
        btntambah.setColor(new java.awt.Color(238, 231, 218));
        btntambah.setColorClick(new java.awt.Color(190, 184, 174));
        btntambah.setColorOver(new java.awt.Color(214, 207, 196));
        btntambah.setcornerRadius(15);
        btntambah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        roundedPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 508, 125, 43));

        cbkategori.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        cbkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frame", "Lensa", "Lainnya" }));
        cbkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkategoriActionPerformed(evt);
            }
        });
        roundedPanel1.add(cbkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 137, 173, 21));

        txtnama.setBackground(new java.awt.Color(238, 231, 218));
        txtnama.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txtnama.setLineColor(new java.awt.Color(238, 231, 218));
        txtnama.setSelectionColor(new java.awt.Color(238, 231, 218));
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        roundedPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 179, 173, 21));

        txthargajual.setBackground(new java.awt.Color(238, 231, 218));
        txthargajual.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        txthargajual.setLineColor(new java.awt.Color(238, 231, 218));
        txthargajual.setSelectionColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(txthargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 305, 173, 21));

        jLabel13.setBackground(new java.awt.Color(238, 231, 218));
        jLabel13.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(238, 231, 218));
        jLabel13.setText("Keterangan");
        roundedPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 394, 111, 21));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtketerangan.setColumns(20);
        txtketerangan.setRows(5);
        jScrollPane1.setViewportView(txtketerangan);

        roundedPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 400, 173, -1));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 118, 1006, 583));

        cancelButton.setForeground(new java.awt.Color(238, 231, 218));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/material-symbols_batal.png"))); // NOI18N
        cancelButton.setText("Batal");
        cancelButton.setColor(new java.awt.Color(136, 171, 142));
        cancelButton.setColorClick(new java.awt.Color(108, 136, 113));
        cancelButton.setColorOver(new java.awt.Color(122, 153, 127));
        cancelButton.setcornerRadius(15);
        cancelButton.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1118, 744, 130, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        Connection conn = new koneksi().getConnection();

        String sql = "insert into barang(kode_barang, kategori, nama, jenis_atau_lensa,  harga_beli, harga_jual, stok, keterangan) values (?,?,?,?,?,?,?,?)";

        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtkode.getText());
            stat.setString(2, cbkategori.getSelectedItem().toString());
            stat.setString(3, txtnama.getText());
            stat.setString(4, txtjenisataulensa.getText());
            stat.setFloat(5, Float.parseFloat(txthargabeli.getText()));
            stat.setFloat(6, Float.parseFloat(txthargajual.getText()));
            stat.setInt(7, Integer.parseInt(txtstok.getText()));
            stat.setString(8, txtketerangan.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtjenisataulensa.requestFocus();

            conn.close();
            stat.close();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan, pesan error: "+e);
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        try {
            // Mengatur look and feel menjadi Nimbus
            UIManager.LookAndFeelInfo[] looks = UIManager.getInstalledLookAndFeels();
            for (UIManager.LookAndFeelInfo look : looks) {
                if ("Nimbus".equals(look.getName())) {
                    UIManager.setLookAndFeel(look.getClassName());
                    break;
                }
            }

            // Buat objek JFrame baru
            JFrame formBarang = new table_model.barang();

            // Tampilkan JFrame baru
            formBarang.setVisible(true);

            // Tutup jendela saat ini
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txthargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargabeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargabeliActionPerformed

    private void cbkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException ignored) {
            Toolkit.getDefaultToolkit().beep();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            ex.printStackTrace();
            return;
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahBarang().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom_palette.RoundedButton btntambah;
    private custom_palette.RoundedButton cancelButton;
    private javax.swing.JComboBox<String> cbkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private custom_palette.RoundedPanel roundedPanel1;
    private custom_palette.RoundedTextField txthargabeli;
    private custom_palette.RoundedTextField txthargajual;
    private custom_palette.RoundedTextField txtjenisataulensa;
    private javax.swing.JTextArea txtketerangan;
    private custom_palette.RoundedTextField txtkode;
    private custom_palette.RoundedTextField txtnama;
    private custom_palette.RoundedTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
